KT_AIVLE_5반_4조/Movie_Web/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path,include

urlpatterns = [
    path('',include('main.urls',namespace='movies')),
    path('admin/', admin.site.urls),
    path('myinfo/', include('myinfo.urls')),
    path('post_detail/', include('post_detail.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

KT_AIVLE_5반_4조/main/urls.py
from django.urls import path,include
from . import views
from .views import MovieList,MovieTag,MovieSearch

app_name = 'movies'
urlpatterns = [
    path('',views.index,name = 'index'),
    path('list/<int:movie_id>', views.movie_detail_list, name = 'list'),
    path('select/',views.select,name = 'select'),
    path('movie_list/',MovieList.as_view(),name = 'movie_list'),
    path('select/<str:genre_tag>',MovieTag.as_view(),name = 'movie_tag'),
    path('search/<str:query>',MovieSearch.as_view(),name = 'movie_search'),
    path('post_detail/', include('post_detail.urls')),
]

KT_AIVLE_5반_4조/myinfo/urls.py
from django.urls import path
from . import views

app_name = 'myinfo'
urlpatterns = [
    
    path('myinfo/', views.myinfo, name='myinfo'),
    path('myinfo/edit', views.myinfo_edit, name='myinfo_edit'),
    path('myinfo/edit/del', views.member_del, name='member_del'),
    path('login/', views.log_in, name='login'),
    path('signup/id_check', views.id_check),
    path('signup/', views.sign_up, name='form_model'),
    path('logout/', views.log_out, name='logout'),

]

KT_AIVLE_5반_4조/myinfo/models.py
from django.db import models

class UserTable(models.Model):
    user_id = models.CharField(primary_key=True, max_length=20, null=False)
    password = models.CharField(max_length=20, null=False)
    email = models.CharField(max_length=50, null=True)
    user_name = models.CharField(max_length=20, null=False)

    def __str__(self):
        return self.user_name

KT_AIVLE_5반_4조/myinfo/forms.py
from django import forms
from .models import UserTable
class SignUpForm(forms.ModelForm):
    class Meta:
        model = UserTable

        fields = ['user_id', 'password', 'user_name']

KT_AIVLE_5반_4조/myinfo/views.py
from re import U
from django.shortcuts import render, redirect
from django.http import JsonResponse
from django.contrib import auth
from django.contrib.auth import authenticate, logout
from django.contrib.auth.models import User
from django.views.decorators.csrf import csrf_exempt
from .models import UserTable
from .forms import SignUpForm

# 로그인
@csrf_exempt
def log_in(request):
    if request.method == 'POST':
        user_id = request.POST.get('user_id')
        password = request.POST.get('password')
        error_message = ''
        
        user = authenticate(request, username=user_id, password=password)

        if user is not None:
            auth.login(request, user)
            request.session['user_id_key'] = UserTable.objects.get(user_id=user_id, password=password).user_id
            return redirect('../../')
        else:
            error_message = '아이디와 비밀번호가 일치하지 않습니다.'
            return render(request, 'myinfo/login.html', {'error_message': error_message})

    return render(request, 'myinfo/login.html')


# 회원가입
@csrf_exempt
def sign_up(request):
    form = SignUpForm(request.POST)

    if request.method == 'POST':
        user_id = request.POST.get('user_id')
        password = request.POST.get('password')
        password_check = request.POST.get('password_check')
        user_name = request.POST.get('user_name')
        email = request.POST.get('email')

        if password == password_check:
            try:
                if User.objects.get(username=user_id):
                    message = '이미 존재하는 아이디입니다.'
                    return render(request, 'myinfo/signup.html', { 'form': form, 'user_id_check': message})
            except:
                User.objects.create_user(username=user_id, password=password)
                user = UserTable(user_id=user_id, password=password, user_name=user_name, email=email)
                user.save()

                return redirect('../login')
        else:
            message = '비밀번호가 일치하지 않습니다. 다시 입력해주세요.'
            return render(request, 'myinfo/signup.html', { 'form': form, 'password_check': message })

    return render(request, 'myinfo/signup.html')

# 아이디 중복체크
def id_check(request):
    user_id = request.GET.get('user_id')
    result = 'fail'
    try:
        check_result =  User.objects.get(username=user_id)
    except:
        check_result = None
    if check_result is None:
        result = 'possible'

    return JsonResponse({ 'result': result })

# 마이페이지(프로필 정보 조회)
@csrf_exempt
def myinfo(request):
    current_user_id = request.session['user_id_key']
    current = UserTable.objects.get(pk = current_user_id)
    context = { 'user_id':current.user_id,'password':current.password, 'email':current.email, 'user_name':current.user_name }
    return render(request, 'myinfo/info.html', context)

# 마이페이지수정(프로필 정보 수정)
@csrf_exempt
def myinfo_edit(request):
    current_user_id = request.session['user_id_key']
    before_info = UserTable.objects.get(pk = current_user_id)
    before_info2 = User.objects.get(username = current_user_id)
  
    if request.method == "POST":
        rewrite_pw = request.POST['new_password']
        rewrite_email = request.POST['new_email']
        
        before_info.password = rewrite_pw
        before_info.email = rewrite_email
        before_info.save()
        before_info2.set_password(rewrite_pw)
        before_info2.save()
        return redirect('/')

    current = UserTable.objects.get(pk = current_user_id)
    context = { 'user_id':current.user_id, 'password':current.password, 'email':current.email, 'user_name':current.user_name }
    return render(request, 'myinfo/info_edit.html', context)

# 회원탈퇴
def member_del(request):
    current_user_id = request.session['user_id_key']
    data1 = UserTable.objects.get(pk = current_user_id)
    data2 = User.objects.get(username = current_user_id)
    data1.delete()
    data2.delete()
    logout(request)
    return redirect('/')

# 로그아웃
def log_out(request):
    logout(request)
    return redirect('/')

KT_AIVLE_5반_4조/myinfo/templates/myinfo/info.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>소문</title>
	<link rel="shortcut icon" type="image/x-icon" href="{% static '/img/logo32x32_line.png' %}">
    <link rel="stylesheet" type="text/css" href="{% static '/css/board.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static '/css/input.css' %}">
	<script src="{% static '/js/jquery.min.js' %}"></script>
	<script src="{% static '/js/input.js' %}"></script>
</head>
<body>
	<header>
		<h1 class="title">마이페이지 📃</h1>
		<nav>
			<img class="logo" src="{% static 'img/logo32x32.png' %}" alt="홈페이지로 돌아가기" onclick="location.href='/'">
		</nav>
	</header>
    
    
    <div id="board_box">
        <ul id="board_form">
            <li>
                <span class="col1">이름  </span>
                <span class="col2">{{ user_name }}</span>
            </li>
            <li>
                <span class="col1">아이디  </span>
                <span class="col2">{{ user_id }}</span>
            </li>
            <li>
                <span class="col1">이메일  </span>
                <span class="col2">{{ email }}</span>
            </li>
        </ul>
    </div>
	    	
    <button type="submit" class="switch" onClick="location.href='{% url 'myinfo:myinfo_edit' %}'" ><span style="text-decoration: double;">수정하기</span></button>
    <button type="submit" class="switch" onClick="location.href='{% url 'myinfo:logout' %}'" ><span style="text-decoration: double;">로그아웃</span></button>
</body>
</html>

KT_AIVLE_5반_4조/myinfo/templates/myinfo/info_edit.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>소문</title>
	<link rel="shortcut icon" type="image/x-icon" href="{% static '/img/logo32x32_line.png' %}">
	<link rel="stylesheet" type="text/css" href="{% static '/css/input.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static '/css/board.css' %}">
	<script src="{% static '/js/jquery.min.js' %}"></script>
	<script src="{% static '/js/input.js' %}"></script>
</head>
<body>
	<header>
		<h1 class="title">마이페이지 수정 ✏️</h1>
		<nav>
			<img class="logo" src="{% static 'img/logo32x32.png' %}" alt="홈페이지로 돌아가기" onclick="location.href='/'">
		</nav>
	</header>
    <form action="{% url 'myinfo:myinfo_edit' %}", method="POST">
        <div id="board_box">
            <ul id="board_form" >
                <h3 id="board_title">
                    비밀번호와 이메일만 수정이 가능합니다.
                </h3>
                <li>
                    <span class="col1">이름  </span>
                    <span class="col2">{{ user_name }}</span>
                </li>
                <li>
                    <span class="col1">아이디  </span>
                    <span class="col2">{{ user_id }}</span>
                </li>
                <li>
                    <span class="col1"><label for="new_password">비밀번호</label></span>
                    <span class="col2"> <input type="text" name="new_password" id="new_password" value = {{ password }} required></span>
                </li>
                <li>
                    <span class="col1"><label for="new_email">이메일</label></span>
                    <span class="col2"> <input type="text" name="new_email" id="new_email" value= {{ email }}></span>
                </li>
            </ul>
        </div>
        <button type="submit" class="switch" ><span style="text-decoration: double;">수정 완료</span></button>
        <button class="switch" ><span style="text-decoration: double;"> <a href="{% url 'myinfo:member_del' %}" style = "color : #fff" >탈퇴하기</a></span></button> 
        
	</form>   
    
</body>
</html>

KT_AIVLE_5반_4조/myinfo/templates/myinfo/login.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>소문</title>
	<link rel="shortcut icon" type="image/x-icon" href="{% static '/img/logo32x32_line.png' %}">
	<link rel="stylesheet" type="text/css" href="{% static '/css/input.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static '/css/board.css' %}">
	<script src="{% static '/js/jquery.min.js' %}"></script>
	<script src="{% static '/js/input.js' %}"></script>
</head>

<body>
	<header>
		<h1 class="title">로그인</h1>
		<nav>
			<img class="logo" src="{% static 'img/logo32x32.png' %}" alt="홈페이지로 돌아가기" onclick="location.href='/'">
		</nav>
	</header>
    <form method='POST'>
		{{error_message}}
    
    <div id="board_box">
        <ul id="board_form" list-style:none;>
            <h3 id="board_title">
                로그인해주세요.
            </h3>
            <li>
                <span class="col1">아이디  </span>
	    		<span class="col2"><input type='text' name='user_id' id='user_id' required></span>
            </li>
            <li>
                <span class="col1" ><label for='password'>비밀번호  </label></span>
	    		<span class="col2"><input type='password' name='password' id='password' required></span>
            </li>
	    </ul>
    
    </div>
        <button id ='login_button' type="submit" class="switch" ><span style="text-decoration: double;">로그인</span></button>
        <button type="submit" class="switch" onClick="location.href='../signup'" ><span style="text-decoration: double;">회원가입하기</span></button>   
    </form>

KT_AIVLE_5반_4조/myinfo/templates/myinfo/signup.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>소문</title>
	<link rel="shortcut icon" type="image/x-icon" href="{% static '/img/logo32x32_line.png' %}">
	<link rel="stylesheet" type="text/css" href="{% static '/css/input.css' %}">
    <script src='https://code.jquery.com/jquery-3.6.0.min.js'></script>
    <script src='https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js'></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
	<script src="{% static '/js/jquery.min.js' %}"></script>
	<script src="{% static '/js/input.js' %}"></script>
</head>


<body>
    <header>
        <h1 class="title">회원가입</h1>
            <nav>
                <img class="logo" src="{% static 'img/logo32x32.png' %}" alt="홈페이지로 돌아가기" onclick="location.href='/'">
            </nav>
    </header>
    <div class='container'>
        <div class='row my-5'>
            <div class='col'>
                <form action='./' method='POST'>
                    {% csrf_token %}
                    <div class='row mx-5'>
                        <div class='col mt-4'>
                            <div class='row  mb-2' id='user_id_check_div'>
                                <h6 class='font-wieght-bold'>아이디</h6>
                                <div class='input-group'>
                                    <input type='text' class='form-control' name='user_id' id='user_id'
                                        value="{{ form.user_id.value | default_if_none:'' }}" placeholder=' 아이디를 입력하세요.' required>
                                    <button color=#feb737 type='button' class='btn btn-outline-secondary' onclick=id_check()>중복확인</button>
                                </div>
                                <small class='mt-1 text-danger' id='id_check_msg'> {{user_id_check}} </small>
                            </div>
                            <div class='row mb-2'>
                                <h6 class='font-wieght-bold'>비밀번호</h6>
                                <input type='password' class='form-control' name='password' id='password'
                                    value="{{ form.password.value | default_if_none:'' }}" placeholder=' 비밀번호를 입력하세요.' required>
                            </div>
                            <div class='row mb-2'>
                                <h6 class='font-wieght-bold'>비밀번호 확인</h6>
                                <input type='password' class='form-control' name='password_check' id='password_check'
                                    placeholder=' 위와 동일한 비밀번호를 입력하세요.' required>
                                <small class='mt-1 text-danger'> {{password_check}} </small>
                            </div>
                            <div class='row mb-4'>
                                <h6 class='font-wieght-bold'>이름</h6>
                                <input type='text' class='form-control' name='user_name' id='user_name'
                                    value="{{ form.user_name.value | default_if_none:'' }}" placeholder=' 이름을 입력하세요.' required>
                                <h6 class='font-wieght-bold' id='user_name_check'></h6>
                            </div>
                            <div class='row mb-4'>
                                <h6 class='font-wieght-bold'>이메일</h6>
                                <input type='text' class='form-control' name='email' id='email' placeholder=' 이메일을 입력하세요.'>
                                <h6 class='font-wieght-bold' id='email_check'></h6>
                            </div>
                        </div>
                    </div>		
                    <div class='row mx-3 justify-content-around'>
                        <a class='btn btn-outline-secondary col mr-1' data-toggle='modal' data-target='#modal'>이전</a>
                        <button class='btn btn-outline-secondary col' id='add_user_button'>회원가입</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div class='modal fade' id='modal' tabindex='-1'>
        <div class='modal-dialog'>
            <div class='modal-content'>
                <div class='modal-header'>
                    <strong>돌아가기</strong>
                    <button type='button' class='close' data-dismiss='modal'>
                        <span>x</span>
                    </button>
                </div>
                <div class='modal-body text-center'>
                    <p>이전 단계로 돌아가시겠습니까?</p>
                    <small>
                        현재 진행단계의 변경사항이 저장되지 않습니다.
                    </small>
                </div>
                <div class='modal-footer justify-content-center'>
                    <button class='btn btn-outline-secondary' data-dismiss='modal'>아니오</button>
                    <a href='../login' class='btn btn-secondary'>&nbsp;&nbsp;&nbsp;예&nbsp;&nbsp;&nbsp;</a>
                </div>
            </div>
        </div>
    </div>
</body>

<script src="https://unpkg.com/axios/dist/axios.min.js"></script>
<script>
	function id_check() {
		let user_id = document.getElementById('user_id').value
		let msg_div = document.getElementById('user_id_check_div')
		let msg = document.getElementById('id_check_msg')

		const ajax = axios({
			url: './id_check',
			method: 'get',
			params: {'user_id': user_id},
			
		})
		ajax.then(function (result) {
			check_result = result['data']['result']
			console.log(check_result)
			if (check_result == 'fail') {
				msg.removeAttribute('class')
				msg.setAttribute('class', 'text-danger')
				msg.innerHTML = '이미 존재하는 아이디입니다.'
				msg_div.append(msg)
			} else {
				msg.removeAttribute('class')
				msg.setAttribute('class', 'text-primary')
				msg.innerHTML = '사용가능한 아이디입니다.'
				msg_div.append(msg)
			}
		})
	}
</script>