KT_AIVLE_5반_4조/Movie_Web/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path,include

urlpatterns = [
    path('',include('main.urls',namespace='movies')),
    path('admin/', admin.site.urls),
    path('myinfo/', include('myinfo.urls')),
    path('post_detail/', include('post_detail.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

KT_AIVLE_5반_4조/main/urls.py
from django.urls import path,include
from . import views
from .views import MovieList,MovieTag,MovieSearch

app_name = 'movies'
urlpatterns = [
    path('',views.index,name = 'index'),
    path('list/<int:movie_id>', views.movie_detail_list, name = 'list'),
    path('select/',views.select,name = 'select'),
    path('movie_list/',MovieList.as_view(),name = 'movie_list'),
    path('select/<str:genre_tag>',MovieTag.as_view(),name = 'movie_tag'),
    path('search/<str:query>',MovieSearch.as_view(),name = 'movie_search'),
    path('post_detail/', include('post_detail.urls')),
]

KT_AIVLE_5반_4조/main/models.py
from django.db import models

GENRE_CHOICES = (

    ('action', 'Action'),
    ('romance', 'Romance'),
    ('horror', 'Horror'),
    ('comedy', 'Comedy'),
    ('drama', 'Drama'),
)


STATUS_CHOICES = (
    ('RA','RECENTLY ADDED'),
    ('MC','MOST COMMENTED'),
    ('TR','TOP RATED'),
)

class Movie(models.Model):
    movie_id = models.AutoField(primary_key=True, null=False)
    movie_title = models.CharField(max_length=100, null=False)
    movie_image_info = models.ImageField(upload_to = 'movies', null=False)
    genre_tag = models.CharField(choices=GENRE_CHOICES,max_length=10, null=False)
    status = models.CharField(choices=STATUS_CHOICES,max_length=2, null=False)
    movie_image_bg = models.ImageField(upload_to = 'images',null = True)

    def __str__(self):
        return self.movie_title

KT_AIVLE_5반_4조/main/views.py
from tkinter import EW
from django.shortcuts import render
from django.views.generic import ListView
from .models import Movie
from post_detail.models import PostTable

class MovieList(ListView):
    model = Movie
    #context_object_name = ''
    #template_name = ''

class MovieSearch(ListView):
    model = Movie

    def get_queryset(self):
        query = self.request.Get.get('q')
        
        if query:
            object_list = self.model.filter(movie_title__icontains = query)
        else :
            object_list = self.model.objects.none()
        return object_list

# 메인페이지
def index(request):
    return render(request,'main/index.html')

# 영화 장르 선택
def select(request):
    return render(request,'main/select.html')

# 영화 장르별 리스트
class MovieTag(ListView):
    model = Movie

    def get_queryset(self):
        self.genre_tag = self.kwargs['genre_tag']
        return Movie.objects.filter(genre_tag = self.genre_tag)

    def get_context_data(self, **kwargs) :
        context = super(MovieTag,self).get_context_data(**kwargs)
        context['top_rated'] = Movie.objects.filter(genre_tag = self.genre_tag).filter(status = "TR")
        context['most_commented'] = Movie.objects.filter(genre_tag = self.genre_tag).filter(status = "MC")
        context['recently_added'] = Movie.objects.filter(genre_tag = self.genre_tag).filter(status = "RA")
        return context

# 영화별 후기 게시판
def movie_detail_list(request, movie_id):
    posts  = PostTable.objects.filter(movie_id=movie_id)
    movie = Movie.objects.get(movie_id=movie_id)
    contents = {'posts':posts, 'movie':movie}
    return render(request, 'main/detail_list_test.html', contents)

KT_AIVLE_5반_4조/main/templates/main/detail_list.html
{% load static %}
<!DOCTYPE html>

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>소문</title>
	<link rel="shortcut icon" type="image/x-icon" href="{% static 'img/logo32x32_line.png' %}">
  <body>
<body>

  <link rel="stylesheet" href="{% static 'css/main_list.css' %}">
  <link rel="stylesheet" href="{% static 'css/media_query.css' %}">
  <link rel="stylesheet" href="{% static 'css/board.css' %}">
  <script src="http://code.jquery.com/jquery-1.11.3.min.js"></script>

  <link href="https://fonts.googleapis.com/css?family=Inter:100,200,300,regular,500,600,700,800,900" rel="stylesheet" />
</head>

<body style="background-color: #43423E;">

  <div class="container">

    <header class="">
      <div class="navbar">

        <button class="navbar-menu-btn">
          <span class="one"></span>
          <span class="two"></span>
          <span class="three"></span>
        </button>

        <nav class="">
          <ul class="navbar-nav">

            <li> <a href="/" class="navbar-link">Home</a> </li>
            <li> <a href="/select/" class="navbar-link">TAG</a> </li>
            <li> <a href="/myinfo/myinfo" class="navbar-link">MyPage</a> </li>

          </ul>
        </nav>

        <div class="navbar-actions">

          <form action="#" class="navbar-form">
            <input type="text" name="search" placeholder="" class="navbar-form-search">

            <button class="navbar-form-btn">
              <ion-icon name="search-outline"></ion-icon>
            </button>

            <button class="navbar-form-close">
              <ion-icon name="close-circle-outline"></ion-icon>
            </button>
          </form>

          <button class="navbar-search-btn">
            <ion-icon name="search-outline"></ion-icon>
          </button>

          <a href="/myinfo/login" class="navbar-signin">
            <span>Sign in</span>
          </a>

        </div>

      </div>
    </header>
    <main>

      <section class="banner">
        <div class="banner-card">
        
          
          <img src=" {% static 'img/1.png' %}"   class="banner-img" alt="">

          <div class="card-content">
            <div class="play">
              <ion-icon name="play-circle-outline"></ion-icon>
            </div>
            <div class="card-info">

              <div class="genre">
                <ion-icon name="film"></ion-icon>
                <span>{{ post.movie_id }}</span>
              </div>

              <div class="year">
                <ion-icon name="calendar"></ion-icon>
                <span>2021</span>
              </div>

              <div class="duration">
                <ion-icon name="time"></ion-icon>
                <span>2h 11m</span>
              </div>

              <div class="quality">4K</div>

            </div>

            <h2 class="card-title">SPIDER MAN : NO WAY HOME</h2>
          </div>
          
        

        </div>
      </section>

      <section class="movies">

        <div class="filter-bar">
          <ul id="board_list_head">
            <li>
              <span class="col1">번호</span>
              <span class="col2">제목</span>
              <span class="col3">작성자</span>
              <span class="col5">작성일</span>
              <span class="col6">추천수</span>
            </li>
          </ul>
        </div>
      </section>

      <section>
        <div id="board_box">
          <ul id="board_list">
            {% for post in object_list %}
            <li>
            <span class="col1">{{ post.post_id }}</span>
            <span class="col2"><a href="/post_detail/{{ post.post_id }}">{{ post.post_title }}</a></span>
            <span class="col3">{{ post.user_id }}</span>
            <span class="col5">{{ post.date.month }}월 {{ post.date.day }}일</span>
            <span class="col6">{{ post.recommender.count }}</span>
            </li>
            {% endfor %}
          </ul> 
        <div id="board_box">
      </section>
    </main>
    
  </div>


  <!--
    - custom js link
  -->
  <script src="{% static 'js/main_list.js' %}"></script>

  <!--
    - ionicon link
  -->
  <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
  <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
</body>

</html>

KT_AIVLE_5반_4조/main/templates/main/detail_list_test.html
{% load static %}
<!DOCTYPE html>

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>소문</title>
	<link rel="shortcut icon" type="image/x-icon" href="{% static 'img/logo32x32_line.png' %}">
  <body>
<body>

  <link rel="stylesheet" href="{% static 'css/main_list.css' %}">
  <link rel="stylesheet" href="{% static 'css/media_query.css' %}">
  <link rel="stylesheet" href="{% static 'css/board.css' %}">
  <script src="http://code.jquery.com/jquery-1.11.3.min.js"></script>

  <link href="https://fonts.googleapis.com/css?family=Inter:100,200,300,regular,500,600,700,800,900" rel="stylesheet" />
</head>

<body style="background-color: #43423E;">

  <div class="container">

    <header class="">
      <div class="navbar">

        <button class="navbar-menu-btn">
          <span class="one"></span>
          <span class="two"></span>
          <span class="three"></span>
        </button>

        <nav class="">
          <ul class="navbar-nav">

            <li> <a href="/" class="navbar-link">Home</a> </li>
            <li> <a href="/select/" class="navbar-link">TAG</a> </li>

          </ul>
        </nav>

        <div class="navbar-actions">

          <form action="#" class="navbar-form">
            <input type="text" name="search" placeholder="" class="navbar-form-search">

            <button class="navbar-form-btn">
              <ion-icon name="search-outline"></ion-icon>
            </button>

            <button class="navbar-form-close">
              <ion-icon name="close-circle-outline"></ion-icon>
            </button>
          </form>

          <button class="navbar-search-btn">
            <ion-icon name="search-outline"></ion-icon>
          </button>
          {% if request.user.is_authenticated %}
            <a href="/myinfo/myinfo" class="navbar-signin"><span>MY PAGE</span></a>
          {% else %}
            <a href="/myinfo/login" class="navbar-signin"><span>LOGIN</span></a>
          {% endif %}


        </div>

      </div>
    </header>
    <main>

      <section class="banner">
        <div class="banner-card">
        
          
          <img src="{{movie.movie_image_bg.url}}"   class="banner-img" alt="">

          <div class="card-content">
            <div class="play">
              <ion-icon name="play-circle-outline"></ion-icon>
            </div>
            <div class="card-info">

              <div class="genre">
                <ion-icon name="film"></ion-icon>
                <span>{{movie.genre_tag}}</span>
              </div>

              <div class="year">
                <ion-icon name="calendar"></ion-icon>
                <span>2021</span>
              </div>

              <div class="duration">
                <ion-icon name="time"></ion-icon>
                <span>2h 11m</span>
              </div>

              <div class="quality">4K</div>

            </div>

            <h2 class="card-title">{{movie.movie_title}}</h2>
          </div>
          
        

        </div>
      </section>

      <section class="movies">

        <div class="filter-bar">
          <ul id="board_list_head">
            <li>
              <span class="col1">번호</span>
              <span class="col2">제목</span>
              <span class="col3">작성자</span>
              <span class="col5">작성일</span>
              <span class="col6">추천수</span>
            </li>
          </ul>
        </div>
      </section>

      <section>
        <div id="board_box">
          <ul id="board_list">
            {% for post in posts %}
            <li>
            <span class="col1">{{ post.post_id }}</span>
            <span class="col2"><a href="/post_detail/{{ post.post_id }}">{{ post.post_title }}</a></span>
            <span class="col3">{{ post.user_name }}</span>
            <span class="col5">{{ post.date.month }}월 {{ post.date.day }}일</span>
            <span class="col6">{{ post.recommender.count }}</span>
            </li>
            {% endfor %}
          </ul> 
        <div id="board_box">
      </section>
    </main>
    
  </div>


  <!--
    - custom js link
  -->
  <script src="{% static 'js/main_list.js' %}"></script>

  <!--
    - ionicon link
  -->
  <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
  <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
</body>

</html>

KT_AIVLE_5반_4조/main/templates/main/index.html
{% load static %}
<!DOCTYPE html>
<html lang="kr">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>소문</title>
	<link rel="shortcut icon" type="image/x-icon" href="{% static 'img/logo32x32_line.png' %}">

	<!-- CSS 연결 -->
	<link rel="stylesheet" type="text/css" href="{% static 'css/jquery.fullPage.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">

	<!-- JS 연결 -->
	<script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
	<script type="text/javascript" src=" {% static 'js/jquery.fullPage.js' %}"></script>
	<script type="text/javascript" src=" {% static 'js/main.js' %}"></script>
</head>
<body>
	
	<button class="switch" onClick="location.href='/select'"><span style="text-decoration: double;">찾아보기</span></button>
	
	<!-- 메인 (fullpage) -->
	<main id="fullpage">
		<!-- 홈페이지 -->
		<section class="section">
			<div class="back">
				<div class="title">
					<h6>당신의 영화 소통의 문이 되어줄</h6>
					<h1>소문</h1><br>
					<h5>	문을 열어 영화를 소문내보세요!		</h5><br><i class="icon-star"></i>
				</div>
				{% if request.user.is_authenticated %}
					<div id="jamb" onclick="location.href='post_detail/my_post_list/'">
				{% else %}
					<div id="jamb" onclick="location.href='myinfo/login'">	
				{% endif %}
					<div class="side" id="side1"></div>
					<div class="side" id="side2"></div>
					<div class="side" id="side3"></div>
					<div class="side" id="side4"></div>
					<div class="crack" id="door">
						<div id="knob"></div>
						<div id="porthole"></div>
					</div>
				</div>
					<div class="text">>> 문을 열어보세요</div>
			</div>
		</section>

		<!-- 소개 페이지 -->
		<section class="section"> 
			<div class="slide">
				<p class="p0"><em> 지금 </em>가장 <em> 핫 </em>한 영화</p>
				<img style="height: 40%;" src=" {% static 'img/rank1.png' %}">
				<p class="p1"><em>#액션</em>  스파이더맨 : 노웨이홈</p>
			</div>
			<div class="slide">
				<p class="p0"><em> 영화에 </em>빠질 수 없는 <em> # 드라마 </em></p>
				<img style="height: 40%;" src=" {% static 'img/King.jpg' %}">
				<p class="p1"><em>#드라마</em>  킹메이커</p>
			</div>
			<div class="slide">
				<p class="p0"> <em> 가볍게 </em>볼 수 있는 <em> # 코미디 </em></p>
				<img style="height: 40%;" src=" {% static 'img/rank2.jpeg' %}">
				<p class="p1"><em>#코미디</em>  해적</p>
			</div>
			<div class="slide">
				<p class="p6"> 영화 <strong> 소통 </strong>의 <strong> 문 </strong>이 되어줄 <br><em>"소문"</em>을 경험해보세요!</p>
				<img src=" {% static 'img/video3.png' %}">
			</div>
		</section>

		<!-- ask & footer -->
		<section class="section fp-auto-height">
			<p class="padding"></p>
			<p class="p0">자세한 문의는 <br>하단의 <em> Github 로고 </em> 를 눌러주세요.</p>
			<a href="https://github.com/kt-aivle-mini-project/movies-up" target="_blank" class="ask"><span style="overflow: hidden;"><img class="github" src="{% static 'img/github.png' %}"></span></a>
			<p class="padding"></p>
			<p class="padding"></p>
			<p class="footer">ⓒ MiniProject 4조</p>
		</section>
</body>
</html>

KT_AIVLE_5반_4조/main/templates/main/movie_list.html
{% load static %}

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css" media="all" />
<script type="text/javascript" src="{% static 'js/jquery-1.4.2.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery-func.js' %}"></script>
<!--[if IE 6]><link rel="stylesheet" href="css/ie6.css" type="text/css" media="all" /><![endif]-->
</head>
<title>소문</title>
<link rel="shortcut icon" type="image/x-icon" href="{% static 'img/logo32x32_line.png' %}">
<body style="background-color: #d5cbdd;">
<!-- START PAGE SOURCE -->
<div id="shell">
  <div id="header">
    <div id="navigation">
      <ul>
        <li><a class="active" href="/">HOME</a></li>
        {% if request.user.is_authenticated %}
          <li><a href="/myinfo/myinfo">MY PAGE</a></li>
				{% else %}
          <li><a href="/myinfo/login">LOGIN</a></li>
				{% endif %}
      </ul>
    </div>
    <div id="sub-navigation">
      <ul>
        <li><a href="{% url 'movies:movie_tag' 'action' %}"># 액션</a></li>
        <li><a href="{% url 'movies:movie_tag' 'horror' %}"># 호러 </a></li>
        <li><a href="{% url 'movies:movie_tag' 'drama' %}"># 드라마</a></li>
        <li><a href="{% url 'movies:movie_tag' 'comedy' %}"># 코미디</a></li>
        <li><a href="{% url 'movies:movie_tag' 'romance' %}"># 로맨스</a></li>
      </ul>
      <div id="search">
        <form action="" method="GET" accept-charset="utf-8">
          <label for="search-field">SEARCH</label>
          <input type="text" name="query" value="{{request.GET.q}}" id="search-field" class="blink search-field"  placeholder="영화 이름을 입력하세요" />
          <input type="submit" value="검색!" class="search-button" />
        </form>
      </div>
    </div>
  </div>
  <div id="main">
    <div id="content">

      <div class="box">
        <div class="head">
            {% if recently_added %}
                <h2>LATEST Movie</h2>
            {% endif %}
            <p class="text-right"><a href="#">See all</a></p>
        </div>

        {% for movie in recently_added%}    
          <div class="movie" onClick="location.href='{% url 'movies:list' movie.movie_id %}'">                               
              <div class="movie-image"><span class="play"><span class="name">{{movie.movie_title}}</span></span><img src="{{movie.movie_image_info.url}}" alt=""></div>
              <div class="rating"><p>RATING</p><div class="stars"><div class="stars-in"></div></div><span class="comments">19</span></div>
          </div>
            {% empty %}
            <h1> 아직 등록된 영화가 없습니다. </h1>
            {% endfor %}
            <div class="cl">&nbsp;</div>
        </div>
      </div>
      <div class="box">
        <div class="head">
          {% if top_rated %}
                <h2>TOP RATED</h2>
          {% endif %}
          <p class="text-right"><a href="#">See all</a></p>
        </div>
        {% for movie in top_rated%}
        <div class="movie" onClick="location.href='{% url 'movies:list' movie.movie_id %}'">
          <div class="movie-image"> <span class="play"><span class="name">{{movie.movie_title}}</span></span> <a href=""><img src="{{movie.movie_image_info.url}}" alt="" /></a> </div>
          <div class="rating">
              <p>RATING</p>
              <div class="stars">
                  <div class="stars-in"> </div>
              </div>
              <span class="comments">19</span> </div>
          </div>
          {% empty %}
          <h1> 아직 등록된 영화가 없습니다. </h1>
          {% endfor %}
          <div class="cl">&nbsp;</div>
        </div>
         
        <div class="box">
          <div class="head">
            {% if most_commented %}
                  <h2>MOST COMMENTED</h2>
            {% endif %}
            <p class="text-right"><a href="#">See all</a></p>
          </div>

          {% for movie in most_commented%}
          <div class="movie" onClick="location.href='{% url 'movies:list' movie.movie_id %}'">
            <div class="movie-image"> <span class="play"><span class="name">{{movie.movie_title}}</span></span> <a href=""><img src="{{movie.movie_image_info.url}}" alt="" /></a> </div>
            <div class="rating">
                <p>RATING</p>
                <div class="stars">
                    <div class="stars-in"> </div>
                </div>
                <span class="comments">19</span> </div>
            </div>
            {% empty %}
            <h1> 아직 등록된 영화가 없습니다. </h1>
            {% endfor %}
            <div class="cl">&nbsp;</div>
          </div>
    </div>
    <div class="cl">&nbsp;</div>
  </div>
  <div id="footer">
<!-- footer 추가예정 -->
  </div>
</div>

</html>

KT_AIVLE_5반_4조/main/templates/main/select.html
{% load static %}
<!DOCTYPE html>
<html lang="kr">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>소문</title>
        <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/logo32x32_line.png' %}">
    
        <!-- CSS 연결 -->
        <link rel="stylesheet" type="text/css" href="{% static 'css/jquery.fullPage.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/select.css' %}">
    
        <!-- JS 연결 -->
        <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
        <script type="text/javascript" src=" {% static 'js/jquery.fullPage.js' %}"></script>
        <script type="text/javascript" src=" {% static 'js/main.js' %}"></script>
    </head>
 
<body style="background-color: #f0dbff;" >
    <div class = "title">
        <h6> 원하는 태그를 선택하세요 </h6>
    </div>
    <div  class = 'tag'>
        <button onClick="location.href='{% url 'movies:movie_tag' 'action' %}'">#액션</button>
        <button onClick="location.href='{% url 'movies:movie_tag' 'horror' %}'" class="horror" >#호러</button>
        <button onClick="location.href='{% url 'movies:movie_tag' 'drama' %}'" class="drama">#드라마</button>
        <button onClick="location.href='{% url 'movies:movie_tag' 'comedy' %}'" class="comedy">#코미디</button>
        <button onClick="location.href='{% url 'movies:movie_tag' 'romance' %}'" class="romance">#로맨스</button>
        {% csrf_token %}
    </div>
</body>
</html>