KT_AIVLE_5반_4조/Movie_Web/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path,include

urlpatterns = [
    path('',include('main.urls',namespace='movies')),
    path('admin/', admin.site.urls),
    path('myinfo/', include('myinfo.urls')),
    path('post_detail/', include('post_detail.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

KT_AIVLE_5반_4조/main/urls.py
from django.urls import path,include
from . import views
from .views import MovieList,MovieTag,MovieSearch

app_name = 'movies'
urlpatterns = [
    path('',views.index,name = 'index'),
    path('list/<int:movie_id>', views.movie_detail_list, name = 'list'),
    path('select/',views.select,name = 'select'),
    path('movie_list/',MovieList.as_view(),name = 'movie_list'),
    path('select/<str:genre_tag>',MovieTag.as_view(),name = 'movie_tag'),
    path('search/<str:query>',MovieSearch.as_view(),name = 'movie_search'),
    path('post_detail/', include('post_detail.urls')),
]

KT_AIVLE_5반_4조/myinfo/urls.py
from django.urls import path
from . import views

app_name = 'myinfo'
urlpatterns = [
    
    path('myinfo/', views.myinfo, name='myinfo'),
    path('myinfo/edit', views.myinfo_edit, name='myinfo_edit'),
    path('myinfo/edit/del', views.member_del, name='member_del'),
    path('login/', views.log_in, name='login'),
    path('signup/id_check', views.id_check),
    path('signup/', views.sign_up, name='form_model'),
    path('logout/', views.log_out, name='logout'),

]

KT_AIVLE_5반_4조/post_detail/urls.py
from django.urls import path
from . import views

app_name = 'post_detail'
urlpatterns = [
    path('<int:post_id>', views.post_detail, name='post_detail'),
    path('post/delete/<int:post_id>', views.post_delete, name='post_delete'),
    path('post/recommend/<int:post_id>', views.post_recommend, name='post_recommend'),
    path('post/detail/comment/delete/<int:comment_id>', views.comment_delete, name='comment_delete'),
    
    path('my_post_list/',views.my_post_list, name='my_post_list'),
    path('post_list/post_new/', views.post_new, name='post_new'),
    path('post_list/edit/<int:post_id>', views.post_edit, name='post_edit'),
]

KT_AIVLE_5반_4조/main/models.py
from django.db import models

GENRE_CHOICES = (

    ('action', 'Action'),
    ('romance', 'Romance'),
    ('horror', 'Horror'),
    ('comedy', 'Comedy'),
    ('drama', 'Drama'),
)


STATUS_CHOICES = (
    ('RA','RECENTLY ADDED'),
    ('MC','MOST COMMENTED'),
    ('TR','TOP RATED'),
)

class Movie(models.Model):
    movie_id = models.AutoField(primary_key=True, null=False)
    movie_title = models.CharField(max_length=100, null=False)
    movie_image_info = models.ImageField(upload_to = 'movies', null=False)
    genre_tag = models.CharField(choices=GENRE_CHOICES,max_length=10, null=False)
    status = models.CharField(choices=STATUS_CHOICES,max_length=2, null=False)
    movie_image_bg = models.ImageField(upload_to = 'images',null = True)

    def __str__(self):
        return self.movie_title

KT_AIVLE_5반_4조/post_detail/models.py
from django.db import models
from myinfo.models import UserTable
from main.models import Movie

class PostTable(models.Model):
    post_id = models.AutoField(primary_key=True, null=False)
    post_title = models.CharField(max_length=50, null=False)
    post_image = models.ImageField(blank=True, upload_to="images/", null=False)
    post_contents = models.TextField(max_length=1000, null=False)
    recommender = models.ManyToManyField(UserTable, blank=True, related_name='recommend_user')
    date = models.DateTimeField(auto_now_add=True, null=False)
    modify_date = models.DateTimeField(null=True, blank=True)
    user_name = models.ForeignKey(UserTable, on_delete=models.CASCADE, related_name='post_user')
    movie_id = models.ForeignKey(Movie, on_delete=models.CASCADE)

    def __str__(self):
        return self.post_title
    
class CommentTable(models.Model):
    comment_id = models.AutoField(primary_key=True, null=False)
    author = models.ForeignKey(UserTable, on_delete=models.CASCADE)
    content = models.TextField(max_length=1000, null=False)
    create_date = models.DateTimeField(auto_now_add=True, null=False)
    post_table = models.ForeignKey(PostTable, on_delete=models.CASCADE)

    def __str__(self):
        return self.author.user_name

KT_AIVLE_5반_4조/post_detail/forms.py
from django import forms
from .models import *
from main.models import Movie

class PostTableForm(forms.ModelForm):
    class Meta:
        model = PostTable

        fields = ['post_title', 'post_image', 'post_contents']

        labels = {
            'post_title' : '제목',
            'post_image' : '이미지',
            'post_contest' : '내용',
        }

class CommentForm(forms.ModelForm):
    class Meta:
        model = CommentTable
        fields = ['content']
        labels = {
            'content': '댓글내용',
        }


class PostForm(forms.ModelForm):
    movie_id_list = forms.ModelChoiceField(queryset=Movie.objects.all(),
    empty_label='Select movie id', required=False)
    # user_id_list = forms.ModelChoiceField(queryset=UserTable.objects.all(),
    # empty_label='Select user id', required=False)

    class Meta:
        model = PostTable
        fields = ('post_title','post_contents','post_image')
        labels = {
            'post_title' : '제목',
            'post_contents' : '내용',
            'post_image' : '이미지',
            # 'movie_id' : '영화 아이디',
            # 'user_id' : '작성자',
        }
        # exclude = ('movie_id', 'user_id',)

class EditForm(forms.ModelForm):
    class Meta:
        model = PostTable
        fields = ('post_title','post_contents','post_image')
        labels = {
            'post_title' : '제목',
            'post_contents' : '내용',
            'post_image' : '이미지',
        }

KT_AIVLE_5반_4조/post_detail/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.csrf import csrf_exempt
from django.utils import timezone
from main.models import *
from myinfo.models import *
from .models import *
from .forms import *

app_name='post_detail'

# 영화 후기 상세 view
@csrf_exempt
def post_detail(request, post_id):
    post = PostTable.objects.get(pk=post_id)
    
    # 댓글 작성 예외처리
    try:
        comments = CommentTable.objects.filter(post_table=post_id)
    except:
        comments = None
    

    if request.method == "POST":
        form = CommentForm(request.POST)
            
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = UserTable.objects.get(user_id=request.user.username)
            comment.post_table = PostTable.objects.get(pk=post_id)
            comment.content = request.POST['content']
            comment.create_date = timezone.now()
            comment.save()
        else:
            return render(request, 'post_detail/post_detail_test.html', {'post':post, 'comments':comments})        
        
    return render(request, 'post_detail/post_detail_test.html', {'post':post, 'comments':comments})

# 영화 후기 삭제 view
@csrf_exempt
def post_delete(request, post_id):
    post = get_object_or_404(PostTable, pk=post_id)
    post.delete()
    return redirect('post_detail:my_post_list')

# 영화 후기 추천 view
@csrf_exempt
def post_recommend(request, post_id):
    post = get_object_or_404(PostTable, pk=post_id)
    user = get_object_or_404(UserTable, pk=request.user)
    
    if user in post.recommender.all():
        post.recommender.remove(user)
        post.save()
    else:
        post.recommender.add(user)
        post.save()
    
    return redirect('post_detail:post_detail', post_id=post.post_id)

# 영화 후기 댓글 삭제 view
def comment_delete(request, comment_id):
    comment = get_object_or_404(CommentTable, pk=comment_id)
    comment.delete()
    return redirect('post_detail:post_detail', post_id=comment.post_table.post_id)

# 작성자 게시물 리스트 페이지
def my_post_list(request):
    posts = PostTable.objects.filter(user_name=request.user.username)
    return render(request, 'post_detail/my_post_list.html',{'posts':posts})

# 게시물 작성 페이지
def post_new(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)       
        if form.is_valid():
            post = form.save(commit=False)
            movie_id = request.POST.getlist('movie_id')[0]
            post.user_name = UserTable.objects.get(user_id=request.user.username)
            post.movie_id = Movie.objects.get(movie_id = movie_id)
            post.save()
            return redirect('post_detail:post_detail',post_id=post.pk)
        else:
            return render(request, 'post_detail/post_new.html', {'form': form})
    else:
        form = PostForm()
    return render(request, 'post_detail/post_new.html',{'form':form})

# 게시물 수정 페이지
def post_edit(request, post_id):
    post = get_object_or_404(PostTable,pk=post_id)
    if request.method == 'POST':
        form = EditForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.user_id = UserTable.objects.get(user_id=request.user.username)
            post.save()
            return redirect('post_detail:post_detail', post_id=post.post_id)
    else:
        form = EditForm(instance=post)
        # form = EditForm(request.POST, request.FILES, instance=post)
    return render(request, 'post_detail/post_edit.html', {'form':form, "post":post})

KT_AIVLE_5반_4조/post_detail/templates/post_detail/my_post_list.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>소문</title>
	<link rel="shortcut icon" type="image/x-icon" href="{% static '/img/logo32x32_line.png' %}">
	<link rel="stylesheet" type="text/css" href="{% static '/css/my_input.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static '/css/board_style.css' %}">
    <script src='https://code.jquery.com/jquery-3.6.0.min.js'></script>
    <script src='https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js'></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
	<script src="{% static '/js/jquery.min.js' %}"></script>
	<script src="{% static '/js/input.js' %}"></script>
</head>


    <body >
        <header>
            <h1 class="title">나의 후기 📚</h1>
                <nav>
                    <img class="logo" src="{% static 'img/logo32x32.png' %}" alt="홈페이지로 돌아가기" onclick="location.href='/'">
                </nav>
        </header>
        <div class="container">
            <div id="board">
        <table id="table_board" class="list">
            <colgroup>
                <col width="150">
                <col width="60%">
                <col width="250">
                <col width="100">
                <col width="150">
            </colgroup>
		<thead >
			<tr>
				<th>번호</th>
				<th>제목</th>
				<th>작성자</th>
				<th>추천</th>
				<th>등록일</th>
			</tr>
		</thead>
            <tbody>
                
                {% for post in posts %}
                <tr>
                    <p >  
                        <td ><a href = "{% url 'post_detail:post_edit' post.post_id %}"> {{post.post_id}} </a></td>
                        <td><a href = "{% url 'post_detail:post_edit' post.post_id %}"> {{post.post_title}}</a></td>
                        <td><a href = "{% url 'post_detail:post_edit' post.post_id %}"> {{post.user_id}}</a></td>
                        <td><a href = "{% url 'post_detail:post_edit' post.post_id %}"> 13</a></td>
                        <td><a href = "{% url 'post_detail:post_edit' post.post_id %}"> {{post.date.month}} / {{post.date.day}} </a> </td>
                        </a>
                    </p>    
                </tr>    
                {% endfor %}
                
            </tbody> 
            <tfoot>
                <tr>
                    <td colspan="5">
                        <a href="../post_list/post_new/">글쓰기  </a>
                    </td>
                </tr>
            </tfoot>
        </table>
    </div>
    </body>
    </html>

KT_AIVLE_5반_4조/post_detail/templates/post_detail/post_detail_test.html
{% load static %}

<link rel="stylesheet" href="{% static 'css/post.css' %}" type="text/css" media="all" />
<link rel="stylesheet" href="{% static 'css/comment.css' %}" type="text/css" media="all" />
<head>
  <title>소문</title>
	<link rel="shortcut icon" type="image/x-icon" href="{% static 'img/logo32x32_line.png' %}">
</head>
<div class="movie-card">
  
    <div class="container">
    {% if post.post_image %}
      <a href="/"><img src="{{ post.post_image.url }}"  alt="cover" class="cover" /></a>
    {% endif %}      
      <div class="hero">
        <div class="details">
        
          <div class="title1">{{ post.post_title }}<span class = "user">{{post.user_name.user_name}}</span></div>
          <div class="title2">{{ post.date }}</div>    
          <fieldset class="rating">
            <input type="radio" id="star5" name="rating" value="5" /><label class = "full" for="star5" title="Awesome - 5 stars"></label>
            <input type="radio" id="star4half" name="rating" value="4 and a half" /><label class="half" for="star4half" title="Pretty good - 4.5 stars"></label>
            <input type="radio" id="star4" name="rating" value="4" checked /><label class = "full" for="star4" title="Pretty good - 4 stars"></label>
            <input type="radio" id="star3half" name="rating" value="3 and a half" /><label class="half" for="star3half" title="Meh - 3.5 stars"></label>
            <input type="radio" id="star3" name="rating" value="3" /><label class = "full" for="star3" title="Meh - 3 stars"></label>
            <input type="radio" id="star2half" name="rating" value="2 and a half" /><label class="half" for="star2half" title="Kinda bad - 2.5 stars"></label>
            <input type="radio" id="star2" name="rating" value="2" /><label class = "full" for="star2" title="Kinda bad - 2 stars"></label>
            <input type="radio" id="star1half" name="rating" value="1 and a half" /><label class="half" for="star1half" title="Meh - 1.5 stars"></label>
            <input type="radio" id="star1" name="rating" value="1" /><label class = "full" for="star1" title="Sucks big time - 1 star"></label>
            <input type="radio" id="starhalf" name="rating" value="half" /><label class="half" for="starhalf" title="Sucks big time - 0.5 stars"></label>
          </fieldset>

          {% if request.user.is_authenticated %}
            <span class="likes" >
            <a href="{% url 'post_detail:post_recommend' post.post_id  %}"
            class="btn btn-sm btn-secondary btn-block my-1">{{ post.recommender.count }}</a> likes</span>
          {% endif %}

        </div> <!-- end details -->
      
    </div> <!-- end hero -->

    <div class="description">
      
        <div class="column1">
          <span class="tag">{{ post.movie_id.get_genre_tag_display }}</span>
        </div> <!-- end column1 -->
        <div class="column2">
            <p> {{ post.post_contents }} 
              {% if post.user_name.user_name == request.user.username %}
                <a href="{% url 'post_detail:post_edit' post.post_id %}">  수정하기  </a>
              {% endif %}
              </p>
        </div> <!-- end column2 -->

    </div> <!-- end description -->


    <!-- Contenedor Principal -->
  <div class="comments-container">
    {% if not user.is_authenticated %}
        <h2>아직 로그인을 안하셨군요? 로그인해서 다양한 의견을 나눠보세요! <a href="{% url 'myinfo:login'%}">  로그인하기  </a></h2>
    {% else %}
        <h2> 댓글을 달아 다양한 의견을 나눠보세요!</h2>
    {% endif %}
    <ul id="comments-list" class="comments-list">
      <li>
        {% for comment in comments %}
        <!-- 댓글 리스트 -->
        <ul class="comments-list reply-list">
            <li>
                <!-- user -->
                <div class="comment-avatar"><img src="{% static 'img/ch.png' %}" alt=""></div>
                <!-- Coment -->
                <div class="comment-box">
                    <div class="comment-head">
                        <h6 class="comment-name">{{ comment.author }}</a></h6>
                        <span>{{ comment.create_date }}</span>
                        {% if request.user.username == comment.author.user_id %}
                            <i class="fa fa-reply"><a href="{% url 'post_detail:comment_delete' comment.comment_id %}" class="btn btn-sm btn-outline-secondary">삭제</a></i>
                        {% endif %}
                        <i class="fa fa-heart"></i>
                    </div>
                    <div class="comment-content">
                        {{ comment.content }}
                    </div>
                </div>
            </li>
        </ul>
      </li>
      {% endfor %}
    </ul>
    {% if user.is_authenticated %}
        <div>
            <br>댓글 작성
            <form action='' method="POST">
                {% csrf_token %}
                <textarea name="content" id="content" name="content" vlaue = ""></textarea><br>
                <button class="primaryContained" type="submit">댓글 추가하기</button> 
            </form>
        </div>
    {% endif %}
  </div>
  </div> <!-- end container -->
</div> <!-- end movie-card -->

KT_AIVLE_5반_4조/post_detail/templates/post_detail/post_edit.html
{% load static %}
<!DOCTYPE html>
<html >
<head>
	<title>소문</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static '/css/bootstrap.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static '/css/font-awesome.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static '/css/animate.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static '/css/hamburgers.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static '/css/animsition.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static '/css/select2.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static '/css/daterangepicker.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static '/css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static '/css/main_input.css' %}">
<!--===============================================================================================-->

<!--===============================================================================================-->
<script src="vendor/jquery/jquery-3.2.1.min.js"></script>
<!--===============================================================================================-->
	<script src="vendor/animsition/js/animsition.min.js"></script>
<!--===============================================================================================-->
	<script src="vendor/bootstrap/js/popper.js"></script>
	<script src="vendor/bootstrap/js/bootstrap.min.js"></script>
<!--===============================================================================================-->
	<script src="vendor/select2/select2.min.js"></script>
<!--===============================================================================================-->
	<script src="vendor/daterangepicker/moment.min.js"></script>
	<script src="vendor/daterangepicker/daterangepicker.js"></script>
<!--===============================================================================================-->
	<script src="vendor/countdowntime/countdowntime.js"></script>
<!--===============================================================================================-->

	<script src="js/main.js"></script>
</head>
<body>


	<div class="container-contact100">

		<div class="wrap-contact100">
			<form class="contact100-form validate-form" id="form1" method="POST" enctype="multipart/form-data">
				{% csrf_token %}
                <span class="contact100-form-title">
					후기 수정하기 📝
				</span>
            
                    <div class="wrap-input100 validate-input" data-validate = "후기 제목을 작성해주세요!">

                        <input class="input100" type="text" name="post_title" value="{{ post.post_title|default_if_none:'' }}">
                        <span class="focus-input100"></span>
                    </div>

                    <div class="wrap-input100 validate-input" data-validate = "이미지를 업로드해주세요!">
                        <input class="input100" type="file" name="post_image"  accept="images/*"  placeholder="이미지 업로드">
                        <span class="focus-input100"></span>
                    </div>

                    <div class="wrap-input100 validate-input" data-validate = "Please enter your post">
                        <textarea class="input100" name="post_contents">{{post.post_contents}}</textarea>
                        <span class="focus-input100"></span>
                    </div>

                    <div class="container-contact100-form-btn" >
                        <button type="submit" class="contact100-form-btn">
                            <span>
                                수정하기!
                            </span>
                        </button>

						<button  class="contact100-form-btn" style="padding: 5x 10px;"> 
                            <span> <a href="{% url 'post_detail:post_delete' post.post_id  %}" style = "color : #fff">삭제하기!</a></span>
						</button>
                    </div>
			</form>
		</div>
	</div>



	<div id="dropDownSelect1"></div>



<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-23581568-13"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-23581568-13');
</script>
<script src="https://unpkg.com/axios/dist/axios.min.js"></script>
</body>
</html>

KT_AIVLE_5반_4조/post_detail/templates/post_detail/post_list.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>소문</title>
	<link rel="shortcut icon" type="image/x-icon" href="{% static '/img/logo32x32_line.png' %}">
	<link rel="stylesheet" type="text/css" href="{% static '/css/my_input.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static '/css/board_style.css' %}">
    <script src='https://code.jquery.com/jquery-3.6.0.min.js'></script>
    <script src='https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js'></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
	<script src="{% static '/js/jquery.min.js' %}"></script>
	<script src="{% static '/js/input.js' %}"></script>
</head>


    <body >
        <header>
            <h1 class="title">나의 후기 📚</h1>
                <nav>
                    <img class="logo" src="{% static 'img/logo32x32.png' %}" alt="홈페이지로 돌아가기" onclick="location.href='/'">
                </nav>
        </header>
        <div class="container">
            <div id="board">
        <table id="table_board" class="list">
            <colgroup>
                <col width="150">
                <col width="60%">
                <col width="250">
                <col width="100">
                <col width="150">
            </colgroup>
		<thead >
			<tr>
				<th>번호</th>
				<th>제목</th>
				<th>작성자</th>
				<th>추천</th>
				<th>등록일</th>
			</tr>
		</thead>
            <tbody>
                
                {% for post in posts %}
                <tr>
                    <p >  
                        <td ><a href = "{% url 'post_detail:post_edit' post.post_id %}"> {{post.post_id}} </a></td>
                        <td><a href = "{% url 'post_detail:post_edit' post.post_id %}"> {{post.post_title}}</a></td>
                        <td><a href = "{% url 'post_detail:post_edit' post.post_id %}"> {{post.user_id}}</a></td>
                        <td><a href = "{% url 'post_detail:post_edit' post.post_id %}"> 13</a></td>
                        <td><a href = "{% url 'post_detail:post_edit' post.post_id %}"> {{post.date.month}} / {{post.date.day}} </a> </td>
                        </a>
                    </p>    
                </tr>    
                {% endfor %}
                
            </tbody> 
            <tfoot>
                <tr>
                    <td colspan="5">
                        <a href="post_new/">글쓰기  </a>
                    </td>
                </tr>
            </tfoot>
        </table>
    </div>
    </body>
    </html>

KT_AIVLE_5반_4조/post_detail/templates/post_detail/post_new.html
{% load static %}
<!DOCTYPE html>
<html >
<head>
	<title>소문</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static '/css/bootstrap.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static '/css/font-awesome.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static '/css/animate.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static '/css/hamburgers.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static '/css/animsition.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static '/css/select2.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static '/css/daterangepicker.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static '/css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static '/css/main_input.css' %}">
<!--===============================================================================================-->

<!--===============================================================================================-->
<script src="vendor/jquery/jquery-3.2.1.min.js"></script>
<!--===============================================================================================-->
	<script src="vendor/animsition/js/animsition.min.js"></script>
<!--===============================================================================================-->
	<script src="vendor/bootstrap/js/popper.js"></script>
	<script src="vendor/bootstrap/js/bootstrap.min.js"></script>
<!--===============================================================================================-->
	<script src="vendor/select2/select2.min.js"></script>
<!--===============================================================================================-->
	<script src="vendor/daterangepicker/moment.min.js"></script>
	<script src="vendor/daterangepicker/daterangepicker.js"></script>
<!--===============================================================================================-->
	<script src="vendor/countdowntime/countdowntime.js"></script>
<!--===============================================================================================-->

	<script src="js/main.js"></script>
</head>
<body>


	<div class="container-contact100">

		<div class="wrap-contact100">
			<form class="contact100-form validate-form" id="form1" method="POST" enctype="multipart/form-data">
				{% csrf_token %}
                <span class="contact100-form-title">
					영화를 소문내보세요! 📝
				</span>
            
                    <div class="wrap-input100 validate-input" data-validate="영화를 선택해주세요!">
                        <select name="movie_id" class = "input100">
                            {% for movie in form.movie_id_list %}
                            {{ movie }}
                            {% endfor %}
                        </select>
                        <span class="focus-input100"></span>
                    </div>

                    <div class="wrap-input100 validate-input" data-validate = "후기 제목을 작성해주세요!">
                        <input class="input100" type="text" name="post_title" placeholder="후기 제목">
                        <span class="focus-input100"></span>
                    </div>

                    <div class="wrap-input100 validate-input" data-validate = "이미지를 업로드해주세요!">
                        <input class="input100" type="file" name="post_image"  accept="images/*"  placeholder="이미지 업로드">
                        <span class="focus-input100"></span>
                    </div>

                    <div class="wrap-input100 validate-input" data-validate = "Please enter your post">
                        <textarea class="input100" name="post_contents" placeholder="영화 후기 작성"></textarea>
                        <span class="focus-input100"></span>
                    </div>

                    <div class="container-contact100-form-btn">
                        <button type="submit" class="contact100-form-btn">
                            <span>
                                작성하기!
                            </span>
                        </button>
                    </div>
			</form>
		</div>
	</div>



	<div id="dropDownSelect1"></div>



<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-23581568-13"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-23581568-13');
</script>

</body>
</html>